### ISSUE TITLE
Attributes PHP 8.0

### ISSUE THREAD

**Issue by idmarinas** [Bukashk0zzz/FilterBundle#11]
Hi:

What about make bundle compatible with PHP 8.0 attributes?

I recently upgraded my project to PHP 8.0 and use attributes, but your bundle is not compatible.

Thx for your bundle.

**Comment by Bukashk0zzz** [comment]
Hi,

I currently do not have plans to update this bundle to support PHP 8.0 attributes.
But feel free to make PR. I will review it and merge it.

**Comment by Bukashk0zzz** [comment]
done in https://github.com/Bukashk0zzz/FilterBundle/pull/12
