### ISSUE TITLE
ToNull filter

### ISSUE THREAD

**Issue by andrconstruction** [Bukashk0zzz/FilterBundle#13]
Case if  I use symfony assert\NotBlank( allowNull : true )  then empty string is not null for an assert  and will applyed next asserts, but if value will be null next asserts will not applyed.
But filter ("ToNull") return empty string instead null 

if incoming an empty string, the filterEntity will skip this value. Becouse exists next condition within Service\Filter.php :

//            if (empty($value)) {
//                continue;
//            }
recomend to comment out this strings

**Comment by andrconstruction** [comment]
example 

#[Filter( parameters: [ 'filter' => 'ToNull' ] )]
		#[Assert\NotBlank( allowNull: true )]
		#[Assert\Length( min: 8, max: 128 )]
		#[Assert\Regex(
			pattern: 'тут паттерн/',
			message: 'Пароль должен содержать минимум одну большую букву, цифру, может также содержать пробел (но не в конце или в начале ) и спецсимволы @ # $ _ - * ^ @ $ ! % * # ? ^ ( [ ) ] . , &'
		)]
		public ?string $password = null;

**Comment by Bukashk0zzz** [comment]
Look like you are right.

Feel free to create PR with these changes. 
If you do this and tests will pass, and I will merge it.

**Comment by andrconstruction** [comment]
Test passed

**Comment by Bukashk0zzz** [comment]
Thanks.

https://github.com/Bukashk0zzz/FilterBundle/releases/tag/v5.0.1
