### ISSUE TITLE
Can we have count() behavior for 7.2 fixed in 1.x branch?

### ISSUE THREAD

**Issue by FractalizeR** [Bukashk0zzz/FilterBundle#3]
Hi. 

We are using your library, but currently on 1.0.x branch. And we are updating our PHP to 7.2. Currently we stumbled upon count() bug due to changed 7.2 behavior:  https://github.com/Bukashk0zzz/FilterBundle/commit/a3620182254b5776e5960c73fc866ecf7d27c782

We would like to have this fixed for 1.x also, not only for 2.x. Is that possible to backport this to 1.x?

**Comment by Bukashk0zzz** [comment]
Hi,

I think yes, pull requests are welcome.

**Comment by FractalizeR** [comment]
Created https://github.com/Bukashk0zzz/FilterBundle/pull/4 but it's target branch needs to be changed.

**Comment by Bukashk0zzz** [comment]
Thank you for PR. I merged it and created new tag https://github.com/Bukashk0zzz/FilterBundle/releases/tag/v1.0.4
