### ISSUE TITLE
Deprecation of tree builder without root node

### ISSUE THREAD

**Issue by jonathangreco** [Bukashk0zzz/FilterBundle#5]
I've encountered a warning today that might be annoying in the near future

![capture d ecran 2019-01-30 a 15 55 17](https://user-images.githubusercontent.com/1587180/51989535-920d6300-24a7-11e9-8b56-7092633fe323.png)

btw thanks for your amazing works on this :) It deserves more stars

**Comment by Bukashk0zzz** [comment]
Hi,

Will try to fix this deprecation on the weekend.

**Comment by Bukashk0zzz** [comment]
Fixed. 
https://github.com/Bukashk0zzz/FilterBundle/releases/tag/v2.0.3

**Comment by jonathangreco** [comment]
thanks a lot :)
