### ISSUE TITLE
static getExtendedTypes() method in %bukashk0zzz_filter.form_type_extension.class% deprecation

### ISSUE THREAD

**Issue by jonathangreco** [Bukashk0zzz/FilterBundle#6]
Hi new (or old) deprecation spotted from 2.0.3

![capture d ecran 2019-01-31 a 14 32 00](https://user-images.githubusercontent.com/1587180/52057392-2be71580-2565-11e9-9acf-b313671694d2.png)

**Comment by Bukashk0zzz** [comment]
That's a new one(  Will fix.

**Comment by Bukashk0zzz** [comment]
Fixed 
https://github.com/Bukashk0zzz/FilterBundle/releases/tag/v2.0.4
